version: "3.8"
services:
  prod:
    image: "jtoper/python-webserver:latest"
    container_name: "prod"
    ports:
      - "80:80"

  stg:
    image: "jtoper/stg-python-webserver:latest"
    container_name: "stg"
    ports:
      - "81:80"
  dev:
    image: "jtoper/dev-python-webserver:latest"
    container_name: "dev"
    ports:
      - "82:80"
  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    container_name: "phpmyadmin"
    ports:
      - "8081:80"
  db:
    image: "jtoper/webserver-db:latest"
    container_name: "db"
    ports:
      - "3308:3306"

networks:
  default:
    name: phpmyadmin_default