version: "3.8"
services:
  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "82:80"
    depends_on:
      - "db"
    networks:
      - app

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "8081:80"
    depends_on:
      - "db"
    networks:
      - app

  db:
    image: "jtoper/webserver-db:latest"
    ports:
      - "3308:3306"
    networks:
      - app
networks:
  app:
    driver: bridge