version: "3.8"
services:
  prod:
    image: "jtoper/python-webserver:latest"
    ports:
      - "80:80"

  stg:
    image: "jtoper/stg-python-webserver:latest"
    ports:
      - "81:80"

  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "82:80"

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "8081:80"

  db:
    image: "jtoper/webserver-db:latest"
    ports:
      - "3308:3306"
