version: "3.8"
services:
  prod:
    image: "jtoper/python-webserver:latest"
    ports:
      - "80:80"
    networks:
      - frontend

  stg:
    image: "jtoper/stg-python-webserver:latest"
    ports:
      - "81:80"
    networks:
      - frontend

  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "82:80"
    networks:
      - frontend

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "8081:80"
    networks:
      - frontend

  db:
    image: "jtoper/webserver-db:latest"
    ports:
      - "3308:3306"
    networks:
      - frontend

networks:
  frontend:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
    attachable: true