version: "3.8"
services:
  dev:
    image: "jtoper/dev-python-webserver:latest"
    expose:
      - 82
    depends_on:
      - "db"
    networks:
      - app

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    expose:
      - 8081
    depends_on:
      - "db"
    networks:
      - app

  db:
    image: "jtoper/webserver-db:latest"
    expose:
      - 3308
    networks:
      - app

networks:
  app:
    driver: overlay