version: "3.8"
services:
  app:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "82:80"
    volumes:
      - .:/app

networks:
  default:
    external: true
    name: phpmyadmin_default