version: "3.8"
services:
  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "0.0.0.0:82:80"
    expose:
      - 82
    depends_on:
      - "db"
    networks:
      - app

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "0.0.0.0:8081:80"
    expose:
      - 8081
    depends_on:
      - "db"
    networks:
      - app

  db:
    image: "jtoper/webserver-db:latest"
    ports:
      - "0.0.0.0:3308:3306"
    expose:
      - 3306
    networks:
      - app

networks:
  app:
    driver: overlay