version: "3.8"
services:
  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "0.0.0.0:82:80"
    depends_on:
      - "db"
    network_mode: "host"

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "0.0.0.0:8081:80"
    depends_on:
      - "db"
    network_mode: "host"

  db:
    image: "jtoper/webserver-db:latest"
    ports:
      - "0.0.0.0:3308:3306"
    network_mode: "host"