version: "3.8"
services:
  dev:
    image: "jtoper/dev-python-webserver:latest"
    ports:
      - "82:80"
    deploy:
      replicas: 1
    depends_on:
      - db
    links:
      - db

  stg:
    image: "jtoper/stg-python-webserver:latest"
    ports:
      - "81:80"
    deploy:
      replicas: 1
    depends_on:
      - db
    links:
      - db

  prod:
    image: "jtoper/python-webserver:latest"
    ports:
      - "80:80"
    deploy:
      replicas: 1
    depends_on:
      - db
    links:
      - db

  phpmyadmin:
    image: "jtoper/phpmyadmin:latest"
    ports:
      - "8081:80"
    depends_on:
      - db
    links:
      - db
  db:
      image: mysql:5.7
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: car_stats
        MYSQL_USER: test
        MYSQL_PASSWORD: root
      ports:
        - "3308:3306"
      volumes:
        - dbdata:/var/lib/mysql
volumes:
  dbdata: