name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest Git image
        uses: actions/checkout@main

      - name: Build Docker Dev img
        run:  docker build . --file Dockerfile --tag dev-python-webserver:$(date +%s)

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: |
            jtoper/dev-python-webserver:latest
          push: ${{ github.ref == 'refs/heads/dev' }}
