name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: |
          python -m pip install -r requirements.txt 
          docker build . --file Dockerfile --tag python-webserver:$(date +%s)
          docker push jtoper/python-webserver:$(date +%s)
