name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Dependency Installation
      uses: py-actions/py-dependency-install@v3.0.0
      with:
          path: "requirements.txt"

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-webserver:$(date +%s)
