name: STG Docker Image Build

on:
  pull_request:
    branches: [ stg ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push STG image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: jtoper/stg-python-webserver:latest
          network: phpmyadmin_default
          file: Dockerfile
          push: true

